package Vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author juanp
 */
public class AdministradorFormularioMenu extends javax.swing.JFrame {

    public JMenuItem getMenu_salir() {
        return menu_salir;
    }

    public JMenuItem getMenu_Administrador_paciente() {
        return menu_Administrador_paciente;
    }

  

    public JMenuItem getMenu_administrador_pacinetemayor() {
        return menu_administrador_pacinetemayor;
    }

    public JMenuItem getMenu_administrador_registrocita() {
        return menu_administrador_registrocita;
    }

    public JMenuItem getMenu_administrador_registromedico() {
        return menu_administrador_registromedico;
    }

    
   

    public static JDesktopPane JDesktopPAne_menu;

    
    public AdministradorFormularioMenu() {
        initComponents();
        this.setTitle("Menu Administrador");
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        JDesktopPAne_menu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.JDesktopPAne_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(JDesktopPAne_menu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_CentroDeCosto = new javax.swing.JMenu();
        menu_Administrador_paciente = new javax.swing.JMenuItem();
        menu_administrador_pacinetemayor = new javax.swing.JMenuItem();
        menu_administrador_registromedico = new javax.swing.JMenuItem();
        menu_administrador_registrocita = new javax.swing.JMenuItem();
        menu_administrador_registroexamen = new javax.swing.JMenuItem();
        menu_administrador_registroexamen1 = new javax.swing.JMenuItem();
        menu_Asignar = new javax.swing.JMenu();
        menu_Asignar_Activo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_Consultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_CentroDeCosto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/nuevo-cliente - copia (2).png"))); // NOI18N
        menu_CentroDeCosto.setText("Registrar");
        menu_CentroDeCosto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_Administrador_paciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Administrador_paciente.setText("Paciente");
        menu_Administrador_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Administrador_pacienteActionPerformed(evt);
            }
        });
        menu_CentroDeCosto.add(menu_Administrador_paciente);

        menu_administrador_pacinetemayor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_administrador_pacinetemayor.setText("Paciente mayor");
        menu_administrador_pacinetemayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_administrador_pacinetemayorActionPerformed(evt);
            }
        });
        menu_CentroDeCosto.add(menu_administrador_pacinetemayor);

        menu_administrador_registromedico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_administrador_registromedico.setText("Medico");
        menu_administrador_registromedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_administrador_registromedicoActionPerformed(evt);
            }
        });
        menu_CentroDeCosto.add(menu_administrador_registromedico);

        menu_administrador_registrocita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_administrador_registrocita.setText("Cita");
        menu_administrador_registrocita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_administrador_registrocitaActionPerformed(evt);
            }
        });
        menu_CentroDeCosto.add(menu_administrador_registrocita);

        menu_administrador_registroexamen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_administrador_registroexamen.setText("Examen");
        menu_administrador_registroexamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_administrador_registroexamenActionPerformed(evt);
            }
        });
        menu_CentroDeCosto.add(menu_administrador_registroexamen);

        menu_administrador_registroexamen1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_administrador_registroexamen1.setText("Programa Especial");
        menu_administrador_registroexamen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_administrador_registroexamen1ActionPerformed(evt);
            }
        });
        menu_CentroDeCosto.add(menu_administrador_registroexamen1);

        jMenuBar1.add(menu_CentroDeCosto);

        menu_Asignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/producto - copia.png"))); // NOI18N
        menu_Asignar.setText("Ver");
        menu_Asignar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_Asignar_Activo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Asignar_Activo.setText("Activo-Empleado");
        menu_Asignar_Activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Asignar_ActivoActionPerformed(evt);
            }
        });
        menu_Asignar.add(menu_Asignar_Activo);

        jMenuBar1.add(menu_Asignar);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/reporte1 - copia.png"))); // NOI18N
        jMenu4.setText("Consultar");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_Consultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Consultar.setText("Consultar");
        menu_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ConsultarActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Consultar);

        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/categorias - copia.png"))); // NOI18N
        jMenu2.setText("Perfil");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        menu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/cerrar-sesion - copia (2).png"))); // NOI18N
        menu_salir.setText("Salir");
        menu_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(menu_salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_ConsultarActionPerformed

    private void menu_Administrador_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Administrador_pacienteActionPerformed
       

    }//GEN-LAST:event_menu_Administrador_pacienteActionPerformed

    private void menu_administrador_registrocitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_administrador_registrocitaActionPerformed
       
    }//GEN-LAST:event_menu_administrador_registrocitaActionPerformed

    private void menu_administrador_pacinetemayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_administrador_pacinetemayorActionPerformed
    
    }//GEN-LAST:event_menu_administrador_pacinetemayorActionPerformed

    private void menu_administrador_registromedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_administrador_registromedicoActionPerformed
      
        
        
        
      
    }//GEN-LAST:event_menu_administrador_registromedicoActionPerformed

    private void menu_Asignar_ActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Asignar_ActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Asignar_ActivoActionPerformed

    private void menu_administrador_registroexamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_administrador_registroexamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_administrador_registroexamenActionPerformed

    private void menu_administrador_registroexamen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_administrador_registroexamen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_administrador_registroexamen1ActionPerformed

    /**
     * @param args the command line argume nts
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_Administrador_paciente;
    private javax.swing.JMenu menu_Asignar;
    private javax.swing.JMenuItem menu_Asignar_Activo;
    private javax.swing.JMenu menu_CentroDeCosto;
    private javax.swing.JMenuItem menu_Consultar;
    private javax.swing.JMenuItem menu_administrador_pacinetemayor;
    private javax.swing.JMenuItem menu_administrador_registrocita;
    private javax.swing.JMenuItem menu_administrador_registroexamen;
    private javax.swing.JMenuItem menu_administrador_registroexamen1;
    private javax.swing.JMenuItem menu_administrador_registromedico;
    private javax.swing.JMenu menu_salir;
    // End of variables declaration//GEN-END:variables
}
