package Vista;


import Conexion.ConexionBD;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ediso
 */
public final class AdministradorActualizarPaciente extends javax.swing.JInternalFrame {

    public int identificacion;
    public JLabel getjLabel_wallpaper() {
        return jLabel_wallpaper;
    }
    
    

    
    public AdministradorActualizarPaciente() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Gestionar Pacientes");
        CargarTablaPaciente();
        
        
        //Cargar tabla
        
        

        //insertar imagen en nuestro JLabel
        ImageIcon wallpaper = new ImageIcon("C:\\Users\\user\\Desktop\\Bases de datos\\fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_paciente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_actualizarpacientenombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_actualizarpacientenacimiento = new javax.swing.JTextField();
        txt_actualizarpacienteestrato = new javax.swing.JTextField();
        txt_actualizarpacienteidentificacion = new javax.swing.JTextField();
        txt_actualizarpacientetelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_actualizarpacientedireccion = new javax.swing.JTextField();
        txt_actualizarpacienteprogramaespecial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_actualizarpacientelugarnacimiento = new javax.swing.JTextField();
        txt_actualizarpacientecorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_actualizarpacientesede = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Pacientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_paciente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        jPanel2.add(jComboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 130, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        txt_actualizarpacientenombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacientenombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefono");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Direccion");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Lugar de nacimiento");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fecha de nacimiento");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Estrato");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 90, -1));

        txt_actualizarpacientenacimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacientenacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 170, -1));

        txt_actualizarpacienteestrato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacienteestrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 170, -1));

        txt_actualizarpacienteidentificacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacienteidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        txt_actualizarpacientetelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacientetelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Identificacion");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        txt_actualizarpacientedireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacientedireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 170, -1));

        txt_actualizarpacienteprogramaespecial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacienteprogramaespecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Programa Especial");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Correo electronico");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, -1));

        txt_actualizarpacientelugarnacimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacientelugarnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 170, -1));

        txt_actualizarpacientecorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacientecorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Sede");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        txt_actualizarpacientesede.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_actualizarpacientesede, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 870, 130));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
     
    }//GEN-LAST:event_jButton_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_actualizar;
    public javax.swing.JButton jButton_eliminar;
    public javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_paciente;
    public javax.swing.JTextField txt_actualizarpacientecorreo;
    public javax.swing.JTextField txt_actualizarpacientedireccion;
    public javax.swing.JTextField txt_actualizarpacienteestrato;
    public javax.swing.JTextField txt_actualizarpacienteidentificacion;
    public javax.swing.JTextField txt_actualizarpacientelugarnacimiento;
    public javax.swing.JTextField txt_actualizarpacientenacimiento;
    public javax.swing.JTextField txt_actualizarpacientenombre;
    public static javax.swing.JTextField txt_actualizarpacienteprogramaespecial;
    public javax.swing.JTextField txt_actualizarpacientesede;
    public javax.swing.JTextField txt_actualizarpacientetelefono;
    // End of variables declaration//GEN-END:variables

public void CargarTablaPaciente(){
    Connection con=new ConexionBD().Conexion();
    DefaultTableModel modelo = new DefaultTableModel();
    String sql="select paciente.id_paciente, paciente.nombre, direccion, telefono, correo_electronico, fecha_nac, lugar_nac, id_estrato, sede.nombre, programa_especial.nombre from paciente,sede,telefono_paciente, correo_electronico,programa_especial, programa_especial_adulto where paciente.id_sede=sede.id_sede AND paciente.id_paciente=telefono_paciente.id_paciente AND paciente.id_paciente=programa_especial_adulto.id_paciente AND programa_especial_adulto.id_programa=programa_especial.id_programa AND paciente.id_paciente=correo_electronico.id_paciente;;";
    Statement st;
    try{
        st= con.createStatement();
        ResultSet rs = st.executeQuery(sql);
        AdministradorActualizarPaciente.jTable_paciente = new JTable(modelo);
        AdministradorActualizarPaciente.jScrollPane1.setViewportView(AdministradorActualizarPaciente.jTable_paciente);
        
        modelo.addColumn("Identificacion");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono(s)");
        modelo.addColumn("Correo(s)");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Lugar Naciemiento");
        modelo.addColumn("Estrato");
        modelo.addColumn("Sede");
        modelo.addColumn("Programa Especial");
        
        while(rs.next()){
            Object fila[] = new Object [10];
            
            for(int i =0; i<10; i++){
                fila [i]=rs.getObject(i+1);
            }
            modelo.addRow(fila);
        }
        con.close();
        
        
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "No fue posible cargar los pacientes");
    }
    jTable_paciente.addMouseListener(new MouseAdapter(){
        @Override
        public void mouseClicked(MouseEvent e){
            int fila_point = jTable_paciente.rowAtPoint(e.getPoint());
            int columna_point=0;
            
            if(fila_point>-1){
                identificacion= (int) modelo.getValueAt(fila_point, columna_point);
                System.out.println(identificacion);
                EnviarDatosPacienteSeleccionado(identificacion);
            }
        }
    });
    
}
private void EnviarDatosPacienteSeleccionado(int id){
    try{
        ConexionBD con=new ConexionBD();
        PreparedStatement pst = con.Conexion().prepareStatement("select paciente.id_paciente AS identificacion, paciente.nombre AS nombre, direccion AS direccion, telefono AS telefono, correo_electronico AS correo, fecha_nac AS fecha_nac, lugar_nac AS lugar_nac, id_estrato AS estrato, sede.nombre AS sede, programa_especial.nombre AS programa from paciente,sede,telefono_paciente, correo_electronico,programa_especial, programa_especial_adulto where paciente.id_sede=sede.id_sede AND paciente.id_paciente=telefono_paciente.id_paciente AND paciente.id_paciente = "+id+";");
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
            txt_actualizarpacienteidentificacion.setText(rs.getString("identificacion"));
            txt_actualizarpacientenombre.setText(rs.getString("nombre"));
            txt_actualizarpacientecorreo.setText(rs.getString("correo"));
            txt_actualizarpacientedireccion.setText(rs.getString("direccion"));
            txt_actualizarpacienteestrato.setText(rs.getString("estrato"));

            txt_actualizarpacientelugarnacimiento.setText(rs.getString("lugar_nac"));
            txt_actualizarpacientenacimiento.setText(rs.getString("fecha_nac"));
            txt_actualizarpacientesede.setText(rs.getString("sede"));
            txt_actualizarpacientetelefono.setText(rs.getString("telefono"));
        }
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "No se pudo llenar");
    }
}
    
    

   
    

   
    

    
    
    
    


   
    

    
    
    
    
    
    
    
    
    
    
    
    
    
}
