package Vista;


import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author juanp
 */
public class AdministradorRegistroMedico extends javax.swing.JInternalFrame {

    public JButton getBotonGuardarmedico() {
        return botonGuardarmedico;
    }

    public JTextField getTxt_Nombremedico() {
        return txt_Nombremedico;
    }

    public JTextField getTxt_direccionmedico() {
        return txt_direccionmedico;
    }

    public JTextField getTxt_fechaingresomedico() {
        return txt_horainiciomedico;
    }

    public JFormattedTextField getTxt_medicofechadenacimiento() {
        return txt_medicofechadenacimiento;
    }

    

    public JTextField getTxt_licenciamedica() {
        return txt_licenciamedica;
    }

    public JTextField getTxt_telefonomedico() {
        return txt_telefonomedico;
    }

    

    public AdministradorRegistroMedico() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Medico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Nombremedico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_direccionmedico = new javax.swing.JTextField();
        txt_telefonomedico = new javax.swing.JTextField();
        txt_licenciamedica = new javax.swing.JTextField();
        txt_horainiciomedico = new javax.swing.JTextField();
        txt_horasalidamedico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_medicofechadenacimiento = new javax.swing.JFormattedTextField();
        txt_fechadeingreso = new javax.swing.JFormattedTextField();
        botonGuardarmedico = new javax.swing.JButton();
        WallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevo Medico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        getContentPane().add(txt_Nombremedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Licencia medica");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de nacimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora salida");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora inicio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, -1));
        getContentPane().add(txt_direccionmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, -1));
        getContentPane().add(txt_telefonomedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, -1));
        getContentPane().add(txt_licenciamedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));
        getContentPane().add(txt_horainiciomedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, -1));
        getContentPane().add(txt_horasalidamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de ingreso");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, -1));

        txt_medicofechadenacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(txt_medicofechadenacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, -1));

        txt_fechadeingreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(txt_fechadeingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

        botonGuardarmedico.setBackground(new java.awt.Color(0, 204, 0));
        botonGuardarmedico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonGuardarmedico.setText("Guardar");
        botonGuardarmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarmedicoActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardarmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        WallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/3409297.jpg"))); // NOI18N
        getContentPane().add(WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarmedicoActionPerformed
       
    }//GEN-LAST:event_botonGuardarmedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WallPaper;
    private javax.swing.JButton botonGuardarmedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_Nombremedico;
    private javax.swing.JTextField txt_direccionmedico;
    private javax.swing.JFormattedTextField txt_fechadeingreso;
    private javax.swing.JTextField txt_horainiciomedico;
    private javax.swing.JTextField txt_horasalidamedico;
    private javax.swing.JTextField txt_licenciamedica;
    private javax.swing.JFormattedTextField txt_medicofechadenacimiento;
    private javax.swing.JTextField txt_telefonomedico;
    // End of variables declaration//GEN-END:variables
}
