package Vista;

import Controlador.ControladorCitaAdmin;
import Controlador.ControladorMedicoAdmin;
import Controlador.ControladorPacienteAdmin;
import Controlador.ControladorPacienteRecibidos;
import Controlador.ControladorPacienteRecibidosSede;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author juanp
 */
public class FormularioMenu extends javax.swing.JFrame {

    public JMenuItem getMenu_salir() {
        return menu_Salir;
    }

    public JMenuItem getMenu_Administrador_paciente() {
        return menu_Administrador_Registrar_Paciente;
    }

  

    public JMenuItem getMenu_administrador_pacinetemayor() {
        return menu_Administrador_Registrar_PacienteMayor;
    }

    public JMenuItem getMenu_administrador_registrocita() {
        return menu_Administrador_Registro_Cita;
    }

    public JMenuItem getMenu_administrador_registromedico() {
        return menu_Administrador_Registrar_Medico;
    }

    
   

    public static JDesktopPane JDesktopPAne_menu;

    
    public FormularioMenu() {
        initComponents();
        this.setTitle("Menu Administrador");
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        JDesktopPAne_menu = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.JDesktopPAne_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(JDesktopPAne_menu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Registrar = new javax.swing.JMenu();
        menu_Administrador_Registrar_Paciente = new javax.swing.JMenuItem();
        menu_Administrador_Registrar_PacienteMayor = new javax.swing.JMenuItem();
        menu_Administrador_Registrar_Medico = new javax.swing.JMenuItem();
        menu_Administrador_Registro_Cita = new javax.swing.JMenuItem();
        menu_Administrador_Registro_Examen = new javax.swing.JMenuItem();
        menu_Administrador_Registro_ProgramaEspecial = new javax.swing.JMenuItem();
        menu_Ver = new javax.swing.JMenu();
        menu_Ver_ExamenesSolicitados = new javax.swing.JMenuItem();
        menu_Ver_Pacientes = new javax.swing.JMenuItem();
        menu_Ver_Pacientes_Recibidos = new javax.swing.JMenuItem();
        menu_Ver_Pacientes_Recibidos1 = new javax.swing.JMenuItem();
        menu_Ver_Medico = new javax.swing.JMenuItem();
        menu_Ver_ = new javax.swing.JMenuItem();
        menu_Consultar = new javax.swing.JMenu();
        menu_Consultar_Cita = new javax.swing.JMenuItem();
        menu_Consultar_Medico = new javax.swing.JMenuItem();
        menu_Consultar_Paciente = new javax.swing.JMenuItem();
        menu_Perfil = new javax.swing.JMenu();
        menu_Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/nuevo-cliente - copia (2).png"))); // NOI18N
        menu_Registrar.setText("Registrar");
        menu_Registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_Administrador_Registrar_Paciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Administrador_Registrar_Paciente.setText("Paciente");
        menu_Administrador_Registrar_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Administrador_Registrar_PacienteActionPerformed(evt);
            }
        });
        menu_Registrar.add(menu_Administrador_Registrar_Paciente);

        menu_Administrador_Registrar_PacienteMayor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Administrador_Registrar_PacienteMayor.setText("Paciente mayor");
        menu_Administrador_Registrar_PacienteMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Administrador_Registrar_PacienteMayorActionPerformed(evt);
            }
        });
        menu_Registrar.add(menu_Administrador_Registrar_PacienteMayor);

        menu_Administrador_Registrar_Medico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Administrador_Registrar_Medico.setText("Medico Titular");
        menu_Administrador_Registrar_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Administrador_Registrar_MedicoActionPerformed(evt);
            }
        });
        menu_Registrar.add(menu_Administrador_Registrar_Medico);

        menu_Administrador_Registro_Cita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Administrador_Registro_Cita.setText("Cita");
        menu_Administrador_Registro_Cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Administrador_Registro_CitaActionPerformed(evt);
            }
        });
        menu_Registrar.add(menu_Administrador_Registro_Cita);

        menu_Administrador_Registro_Examen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Administrador_Registro_Examen.setText("Examen");
        menu_Administrador_Registro_Examen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Administrador_Registro_ExamenActionPerformed(evt);
            }
        });
        menu_Registrar.add(menu_Administrador_Registro_Examen);

        menu_Administrador_Registro_ProgramaEspecial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Administrador_Registro_ProgramaEspecial.setText("Programa Especial");
        menu_Administrador_Registro_ProgramaEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Administrador_Registro_ProgramaEspecialActionPerformed(evt);
            }
        });
        menu_Registrar.add(menu_Administrador_Registro_ProgramaEspecial);

        jMenuBar1.add(menu_Registrar);

        menu_Ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/producto - copia.png"))); // NOI18N
        menu_Ver.setText("Ver");
        menu_Ver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_Ver_ExamenesSolicitados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Ver_ExamenesSolicitados.setText("Examenes Solicitados");
        menu_Ver_ExamenesSolicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ver_ExamenesSolicitadosActionPerformed(evt);
            }
        });
        menu_Ver.add(menu_Ver_ExamenesSolicitados);

        menu_Ver_Pacientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Ver_Pacientes.setText("Pacientes");
        menu_Ver_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ver_PacientesActionPerformed(evt);
            }
        });
        menu_Ver.add(menu_Ver_Pacientes);

        menu_Ver_Pacientes_Recibidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Ver_Pacientes_Recibidos.setText("Pacientes Recibidos");
        menu_Ver_Pacientes_Recibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ver_Pacientes_RecibidosActionPerformed(evt);
            }
        });
        menu_Ver.add(menu_Ver_Pacientes_Recibidos);

        menu_Ver_Pacientes_Recibidos1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Ver_Pacientes_Recibidos1.setText("Pacientes Recibidos Sede");
        menu_Ver_Pacientes_Recibidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ver_Pacientes_Recibidos1ActionPerformed(evt);
            }
        });
        menu_Ver.add(menu_Ver_Pacientes_Recibidos1);

        menu_Ver_Medico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Ver_Medico.setText("Medico");
        menu_Ver_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ver_MedicoActionPerformed(evt);
            }
        });
        menu_Ver.add(menu_Ver_Medico);

        menu_Ver_.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Ver_.setText("Ver...");
        menu_Ver_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Ver_ActionPerformed(evt);
            }
        });
        menu_Ver.add(menu_Ver_);

        jMenuBar1.add(menu_Ver);

        menu_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/reporte1 - copia.png"))); // NOI18N
        menu_Consultar.setText("Consultar");
        menu_Consultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menu_Consultar_Cita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Consultar_Cita.setText("Cita");
        menu_Consultar_Cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Consultar_CitaActionPerformed(evt);
            }
        });
        menu_Consultar.add(menu_Consultar_Cita);

        menu_Consultar_Medico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Consultar_Medico.setText("Medico");
        menu_Consultar_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Consultar_MedicoActionPerformed(evt);
            }
        });
        menu_Consultar.add(menu_Consultar_Medico);

        menu_Consultar_Paciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu_Consultar_Paciente.setText("Paciente");
        menu_Consultar_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Consultar_PacienteActionPerformed(evt);
            }
        });
        menu_Consultar.add(menu_Consultar_Paciente);

        jMenuBar1.add(menu_Consultar);

        menu_Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/categorias - copia.png"))); // NOI18N
        menu_Perfil.setText("Perfil");
        menu_Perfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(menu_Perfil);

        menu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/cerrar-sesion - copia (2).png"))); // NOI18N
        menu_Salir.setText("Salir");
        menu_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(menu_Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_Consultar_CitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Consultar_CitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Consultar_CitaActionPerformed

    private void menu_Administrador_Registrar_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Administrador_Registrar_PacienteActionPerformed
       AdministradorRegistropaciente a=new AdministradorRegistropaciente();
        ControladorPacienteAdmin cPaciente= new ControladorPacienteAdmin(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);

    }//GEN-LAST:event_menu_Administrador_Registrar_PacienteActionPerformed

    private void menu_Administrador_Registro_CitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Administrador_Registro_CitaActionPerformed
         
        AdministradorRegistroCita a=new AdministradorRegistroCita();
        ControladorCitaAdmin mc= new ControladorCitaAdmin(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);
    }//GEN-LAST:event_menu_Administrador_Registro_CitaActionPerformed

    private void menu_Administrador_Registrar_PacienteMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Administrador_Registrar_PacienteMayorActionPerformed
    
    }//GEN-LAST:event_menu_Administrador_Registrar_PacienteMayorActionPerformed

    private void menu_Administrador_Registrar_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Administrador_Registrar_MedicoActionPerformed
       
        AdministradorRegistroMedico a=new AdministradorRegistroMedico();
        ControladorMedicoAdmin mc= new ControladorMedicoAdmin(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);
        
        
      
    }//GEN-LAST:event_menu_Administrador_Registrar_MedicoActionPerformed

    private void menu_Ver_ExamenesSolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ver_ExamenesSolicitadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Ver_ExamenesSolicitadosActionPerformed

    private void menu_Administrador_Registro_ExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Administrador_Registro_ExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Administrador_Registro_ExamenActionPerformed

    private void menu_Administrador_Registro_ProgramaEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Administrador_Registro_ProgramaEspecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Administrador_Registro_ProgramaEspecialActionPerformed

    private void menu_Ver_Pacientes_RecibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ver_Pacientes_RecibidosActionPerformed
        AdministradorVerPacientesRecibidos a=new AdministradorVerPacientesRecibidos();
        ControladorPacienteRecibidos c= new ControladorPacienteRecibidos(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);
    }//GEN-LAST:event_menu_Ver_Pacientes_RecibidosActionPerformed

    private void menu_Consultar_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Consultar_MedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Consultar_MedicoActionPerformed

    private void menu_Consultar_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Consultar_PacienteActionPerformed
       AdministradorVerPacientesRecibidos3 a=new AdministradorVerPacientesRecibidos3();
        ControladorPacienteRecibidos3 c= new ControladorPacienteRecibidos3(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);
    }//GEN-LAST:event_menu_Consultar_PacienteActionPerformed

    private void menu_Ver_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ver_MedicoActionPerformed
        // TODO add your handling code here:
        AdministradorVerMedicoTitular a=new AdministradorVerMedicoTitular();
        ControladorMedicoAdmin c= new ControladorMedicoAdmin(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);
        
    }//GEN-LAST:event_menu_Ver_MedicoActionPerformed

    private void menu_Ver_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ver_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Ver_ActionPerformed

    private void menu_Ver_PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ver_PacientesActionPerformed
        AdministradorActualizarPaciente a=new AdministradorActualizarPaciente();
        ControladorPacienteAdmin cPaciente=new ControladorPacienteAdmin(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_Ver_PacientesActionPerformed

    private void menu_Ver_Pacientes_Recibidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Ver_Pacientes_Recibidos1ActionPerformed
        AdministradorVerPacientesRecibidosSede a=new AdministradorVerPacientesRecibidosSede();
        ControladorPacienteRecibidosSede c= new ControladorPacienteRecibidosSede(a);
        a.setVisible(true);
        JDesktopPAne_menu.add(a);
    }//GEN-LAST:event_menu_Ver_Pacientes_Recibidos1ActionPerformed

    /**
     * @param args the command line argume nts
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_Administrador_Registrar_Medico;
    private javax.swing.JMenuItem menu_Administrador_Registrar_Paciente;
    private javax.swing.JMenuItem menu_Administrador_Registrar_PacienteMayor;
    private javax.swing.JMenuItem menu_Administrador_Registro_Cita;
    private javax.swing.JMenuItem menu_Administrador_Registro_Examen;
    private javax.swing.JMenuItem menu_Administrador_Registro_ProgramaEspecial;
    private javax.swing.JMenu menu_Consultar;
    private javax.swing.JMenuItem menu_Consultar_Cita;
    private javax.swing.JMenuItem menu_Consultar_Medico;
    private javax.swing.JMenuItem menu_Consultar_Paciente;
    private javax.swing.JMenu menu_Perfil;
    private javax.swing.JMenu menu_Registrar;
    private javax.swing.JMenu menu_Salir;
    private javax.swing.JMenu menu_Ver;
    private javax.swing.JMenuItem menu_Ver_;
    private javax.swing.JMenuItem menu_Ver_ExamenesSolicitados;
    private javax.swing.JMenuItem menu_Ver_Medico;
    private javax.swing.JMenuItem menu_Ver_Pacientes;
    private javax.swing.JMenuItem menu_Ver_Pacientes_Recibidos;
    private javax.swing.JMenuItem menu_Ver_Pacientes_Recibidos1;
    // End of variables declaration//GEN-END:variables
}
