package Vista;


import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author juanp
 */
public class RegistroCita extends javax.swing.JInternalFrame {

    public JButton getBotonGuardarpaciente() {
        return botonGuardarpaciente;
    }

    public JComboBox<String> getComboBoxcitamedico() {
        return ComboBoxcitamedico;
    }

    public JComboBox<String> getComboBoxexamencita() {
        return ComboBoxexamencita;
    }

    public JTextField getTxt_citacorreoelectronico() {
        return txt_citacorreoelectronico;
    }

    public JTextField getTxt_citafechayhoracita() {
        return txt_citafechayhoracita;
    }

    public JTextField getTxt_citamodalidad() {
        return txt_citamodalidad;
    }

    public JTextField getTxt_citasede() {
        return txt_citasede;
    }

    public JTextField getTxt_citatelefono() {
        return txt_citatelefono;
    }

    public JTextField getTxt_diagnosticocita() {
        return txt_diagnosticocita;
    }

    public JTextField getTxt_idcita() {
        return txt_idcita;
    }

   

    

    public RegistroCita() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Nueva Cita");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_idcita = new javax.swing.JTextField();
        txt_citafechayhoracita = new javax.swing.JTextField();
        txt_citamodalidad = new javax.swing.JTextField();
        txt_diagnosticocita = new javax.swing.JTextField();
        txt_citasede = new javax.swing.JTextField();
        txt_citacorreoelectronico = new javax.swing.JTextField();
        ComboBoxexamencita = new javax.swing.JComboBox<>();
        ComboBoxcitamedico = new javax.swing.JComboBox<>();
        botonGuardarpaciente = new javax.swing.JButton();
        WallPaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva Cita");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Cita");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Diagnostico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modalidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha y Hora");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Medico");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sede");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Examen");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Correo Electronico");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, -1));
        getContentPane().add(txt_idcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, -1));
        getContentPane().add(txt_citafechayhoracita, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, -1));
        getContentPane().add(txt_citamodalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, -1));
        getContentPane().add(txt_diagnosticocita, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));
        getContentPane().add(txt_citasede, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));
        getContentPane().add(txt_citacorreoelectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, -1));

        ComboBoxexamencita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analisis de orina", "Analisis de popis", "Analisis de sangre", "Pruebas de laboratorio", "Pruebas geneticas", "Ecografias", " ", " " }));
        ComboBoxexamencita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxexamencitaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxexamencita, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, -1));

        ComboBoxcitamedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBoxcitamedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, -1));

        botonGuardarpaciente.setBackground(new java.awt.Color(0, 204, 0));
        botonGuardarpaciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonGuardarpaciente.setText("Guardar");
        botonGuardarpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarpacienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardarpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        WallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/3409297.jpg"))); // NOI18N
        getContentPane().add(WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarpacienteActionPerformed
       
    }//GEN-LAST:event_botonGuardarpacienteActionPerformed

    private void ComboBoxexamencitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxexamencitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxexamencitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxcitamedico;
    private javax.swing.JComboBox<String> ComboBoxexamencita;
    private javax.swing.JLabel WallPaper;
    private javax.swing.JButton botonGuardarpaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_citacorreoelectronico;
    private javax.swing.JTextField txt_citafechayhoracita;
    private javax.swing.JTextField txt_citamodalidad;
    private javax.swing.JTextField txt_citasede;
    private javax.swing.JTextField txt_diagnosticocita;
    private javax.swing.JTextField txt_idcita;
    // End of variables declaration//GEN-END:variables
}
